# The following enables several GHC versions to be tested; often it's enough to
# test only against the last release in a major GHC version. Feel free to omit
# lines listings versions you don't need/want testing for.
language: haskell
ghc:
  - "7.10.3"
  - "8.2.2"
  - "8.4.4"

env:
 - GTKVER=2
 - GTKVER=3

# Note: the distinction between `before_install` and `install` is not important.
before_install:
 - cd gtk$GTKVER/

install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq libgtk2.0-dev libglib2.0-dev libgtk-3-dev
 - travis_retry sudo apt-get install -qq alex-3.1.4 happy-1.19.5
 - export PATH=$HOME/.cabal/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH
 - travis_retry cabal update

script:
 - travis_retry cabal install --run-tests -v -j1

notifications:
 email: true

branches:
    only:
          - master
          - /^develop.*/

deploy:
  provider: hackage
  username: keera_studios_ci
  password:
    secure: qRdGcL5+9Icow880LbaTNQMq4UyqNsI98HZHtuKfiZCsXwIeEW9jsTiUZC0EuE2ZKLWscHdfqd531A+wWXiHxC2sAJ8woVNLcOu+URphBzpAkvJMAYCZGhAQhzm3xllyVcg2USDr2vVgn02mTDcZmmiK6ztDHqibxC+D54eDIkNpCEiLaR24zp7ErlzyoVDOkFSfN4tWAAUCgTunjg17Hn/UxEBdPjcpCg9UXrl/BzdWbqPYkxh1OI3Gl+3yvQh07f3ub6PhiCSQWYIO6q94b2F2h+FBLRq8vupgg5wd+wF8tmiCYsJx8k3UCi9v2Oh6XTb+xtO0nL/c3+vrV+Dcw5hBSDjSZ5TpSE8U7jDajkWRZhpLUlrUyMbLQhJH9QY+asxVlmr6sSnf3D//AQKYFptm+ovmdlWE3jxJ99PRSVW6efaLvedvf2VOL7ZtwBYZOd1QGXkBDAsDEv/LxPql4BeLYHTgVVO9bjYOpvSM9oC2gNCDQzOJlb8HUfSG721HIngZmAE7BpjTQhCatYdauW236brddXQEpSEQxfEJbcsoZWrO2kD7GO9EzVfaV1OrOgJf2IBZTLEXlEMpUzG26lrCs+cb0NpReRyZWZMEH04uX/yhHVlA3pSiQLB2u0fsmmRjvwzstTnvzEN9HpPksw36mgUKgzF+y4KMKDcL7d4=
  on:
    branch: master
    condition:
      - ${TRAVIS_HASKELL_VERSION}=8.4.4
